server:
  port: 9999

spring:
  cloud:
    stream:
      bindings:
        output: accounts

user:
  path: /user/**
    url: http://localhost:11111/uaa/user

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
netflix:
  atlas:
    uri: http://atlas:7101/api/v1/publish



