server:
  port: 9998

spring:
  cloud:
    stream:
      bindings:
        output: reservations

  
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
netflix:
  atlas:
    uri: http://atlas:7101/api/v1/publish

